# controllers:
#     resource: ../../src/Controller/
#     type: annotation
web_controllers:
    resource: ../../src/Controller/Web/
    type: annotation
rest_controllers:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api